"""
Utility functions including word lookup table for random filename suffixes.
"""

import random
from typing import List

# Word lookup table for random filename suffixes
# These words will be combined with random numbers (00-99) to create unique suffixes
WORD_LOOKUP_TABLE: List[str] = [
    "eagle",
    "tiger",
    "ocean",
    "forest",
    "river",
    "mountain",
    "valley",
    "desert",
    "canyon",
    "island",
    "beach",
    "cloud",
    "storm",
    "thunder",
    "lightning",
    "rainbow",
    "sunset",
    "sunrise",
    "moon",
    "star",
    "galaxy",
    "planet",
    "comet",
    "meteor",
    "crystal",
    "diamond",
    "pearl",
    "ruby",
    "sapphire",
    "emerald",
    "amber",
    "jade",
    "flame",
    "spark",
    "ember",
    "glow",
    "shine",
    "bright",
    "radiant",
    "luminous",
    "shadow",
    "mist",
    "fog",
    "breeze",
    "wind",
    "gale",
    "hurricane",
    "tornado",
    "wave",
    "tide",
    "current",
    "stream",
    "brook",
    "creek",
    "lake",
    "pond",
    "cliff",
    "peak",
    "ridge",
    "summit",
    "base",
    "foothill",
    "plateau",
    "plain",
    "meadow",
    "prairie",
    "savanna",
    "tundra",
    "jungle",
    "swamp",
    "marsh",
    "bog",
    "cave",
    "cavern",
    "tunnel",
    "passage",
    "chamber",
    "hall",
    "corridor",
    "path",
    "trail",
    "road",
    "way",
    "route",
    "journey",
    "voyage",
    "adventure",
    "quest",
    "treasure",
    "artifact",
    "relic",
    "token",
    "symbol",
    "emblem",
    "badge",
    "mark",
    "sign",
    "signal",
    "beacon",
    "lighthouse",
    "tower",
    "castle",
    "fortress",
    "citadel",
    "temple",
    "shrine",
    "sanctuary",
    "haven",
    "refuge",
    "shelter",
    "harbor",
    "port",
    "vessel",
    "ship",
    "boat",
    "craft",
    "vehicle",
    "chariot",
    "carriage",
    "wagon",
    "steed",
    "stallion",
    "mare",
    "colt",
    "foal",
    "pony",
    "unicorn",
    "pegasus",
    "dragon",
    "phoenix",
    "griffin",
    "sphinx",
    "kraken",
    "leviathan",
    "serpent",
    "viper",
    "hawk",
    "falcon",
    "raven",
    "crow",
    "owl",
    "eagle",
    "condor",
    "vulture",
    "wolf",
    "fox",
    "bear",
    "lion",
    "panther",
    "jaguar",
    "leopard",
    "cheetah",
    "deer",
    "elk",
    "moose",
    "bison",
    "buffalo",
    "antelope",
    "gazelle",
    "zebra",
    "elephant",
    "rhino",
    "hippo",
    "crocodile",
    "alligator",
    "turtle",
    "tortoise",
    "lizard",
    "snake",
    "python",
    "cobra",
    "mamba",
    "viper",
    "rattlesnake",
    "boa",
    "anaconda",
    "shark",
    "whale",
    "dolphin",
    "seal",
    "otter",
    "beaver",
    "muskrat",
    "platypus",
    "penguin",
    "seagull",
    "pelican",
    "flamingo",
    "crane",
    "heron",
    "stork",
    "ibis",
    "parrot",
    "macaw",
    "cockatoo",
    "toucan",
    "hummingbird",
    "kingfisher",
    "woodpecker",
    "finch",
    "sparrow",
    "robin",
    "cardinal",
    "bluejay",
    "mockingbird",
    "thrush",
    "wren",
    "warbler",
    "butterfly",
    "moth",
    "dragonfly",
    "damselfly",
    "beetle",
    "ladybug",
    "firefly",
    "cricket",
    "grasshopper",
    "cicada",
    "locust",
    "mantis",
    "ant",
    "bee",
    "wasp",
    "hornet",
    "spider",
    "scorpion",
    "centipede",
    "millipede",
    "worm",
    "slug",
    "snail",
    "clam",
    "oyster",
    "mussel",
    "scallop",
    "abalone",
    "conch",
    "nautilus",
    "octopus",
    "squid",
    "cuttlefish",
    "jellyfish",
    "coral",
    "anemone",
    "starfish",
    "urchin",
    "sea cucumber",
    "barnacle",
    "crab",
    "lobster",
    "shrimp",
    "prawn",
    "crayfish",
    "krill",
    "plankton",
    "algae",
    "kelp",
    "seaweed",
    "moss",
    "fern",
    "ivy",
    "vine",
    "creeper",
    "tendril",
    "root",
    "stem",
    "branch",
    "twig",
    "leaf",
    "petal",
    "bloom",
    "blossom",
    "bud",
    "sprout",
    "seed",
    "nut",
    "berry",
    "fruit",
    "apple",
    "orange",
    "lemon",
    "lime",
    "grape",
    "cherry",
    "plum",
    "peach",
    "apricot",
    "nectarine",
    "mango",
    "papaya",
    "pineapple",
    "coconut",
    "banana",
    "plantain",
    "date",
    "fig",
    "pomegranate",
    "persimmon",
    "kiwi",
    "dragonfruit",
    "passionfruit",
    "guava",
    "lychee",
    "rambutan",
    "durian",
    "jackfruit",
    "breadfruit",
    "starfruit",
    "carambola",
    "soursop",
    "custard apple",
    "sugar apple",
    "rose",
    "lily",
    "tulip",
    "daisy",
    "sunflower",
    "dandelion",
    "clover",
    "thistle",
    "lavender",
    "jasmine",
    "gardenia",
    "magnolia",
    "cherry blossom",
    "dogwood",
    "azalea",
    "rhododendron",
    "hydrangea",
    "peony",
    "chrysanthemum",
    "marigold",
    "zinnia",
    "petunia",
    "pansy",
    "viola",
    "snapdragon",
    "foxglove",
    "larkspur",
    "delphinium",
    "lupine",
    "sweet pea",
    "morning glory",
    "honeysuckle",
    "wisteria",
    "jasmine",
    "jasmine",
    "honeysuckle",
    "clematis",
    "bougainvillea",
    "passionflower",
    "trumpet vine",
    "cactus",
    "succulent",
    "aloe",
    "agave",
    "yucca",
    "prickly pear",
    "barrel cactus",
    "saguaro",
    "palm",
    "coconut palm",
    "date palm",
    "fan palm",
    "royal palm",
    "queen palm",
    "areca palm",
    "bamboo palm",
    "oak",
    "maple",
    "birch",
    "pine",
    "cedar",
    "fir",
    "spruce",
    "hemlock",
    "redwood",
    "sequoia",
    "cypress",
    "juniper",
    "yew",
    "holly",
    "boxwood",
    "laurel",
    "willow",
    "poplar",
    "aspen",
    "elm",
    "ash",
    "beech",
    "chestnut",
    "walnut",
    "hickory",
    "pecan",
    "hazel",
    "alder",
    "sycamore",
    "plane",
    "linden",
    "basswood",
    "magnolia",
    "dogwood",
    "redbud",
    "crabapple",
    "cherry",
    "plum",
    "pear",
    "apple",
    "peach",
    "apricot",
    "nectarine",
    "almond",
    "pistachio",
    "cashew",
    "brazil nut",
    "macadamia",
    "pine nut",
    "sunflower seed",
    "pumpkin seed",
    "sesame seed",
    "flax seed",
    "chia seed",
    "hemp seed",
    "quinoa",
    "rice",
    "wheat",
    "barley",
    "oats",
    "rye",
    "corn",
    "millet",
    "sorghum",
    "buckwheat",
    "amaranth",
    "teff",
    "fonio",
    "wild rice",
    "black rice",
    "red rice",
    "brown rice",
    "jasmine rice",
    "basmati rice",
    "arborio rice",
    "sushi rice",
    "sticky rice",
    "glutinous rice",
    "sweet rice",
    "forbidden rice",
]


def generate_random_suffix() -> str:
    """
    Generate a random suffix using word from lookup table + random number.

    Returns:
        Random suffix in format: word + number (e.g., "eagle73", "tiger42")
    """
    word = random.choice(WORD_LOOKUP_TABLE)
    number = random.randint(0, 99)
    return f"{word}{number:02d}"


def get_default_file_extensions() -> List[str]:
    """
    Get the default list of file extensions to process.

    Returns:
        List of file extensions (with leading dots)
    """
    return [
        ".pdf",
        ".cbr",
        ".cbz",  # PDFs and comic files
        ".epub",
        ".mobi",
        ".azw",
        ".azw3",  # Common ebook formats
        ".fb2",
        ".lit",
        ".prc",  # Other ebook formats
        ".txt",
        ".rtf",  # Text formats
        ".djvu",
        ".chm",  # Document formats
        ".html",
        ".htm",  # Web formats
    ]
